# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def start(self):
        points1 = 0
        points2 = 0
        points3 = 0
        points4 = 0
        points5 = 0
        if self.radioButton.isChecked():
            points1+=10
        elif self.radioButton_2.isChecked():
            points2+=10
        elif self.radioButton_22.isChecked():
            points3+=10
        elif self.radioButton_23.isChecked():
            points4+=10
        elif self.radioButton_24.isChecked():
            points5+=10
        elif self.radioButton_4.isChecked():
            points1+=10
        elif self.radioButton_25.isChecked():
            points2+=10
        elif self.radioButton_26.isChecked():
            points3+=10
        elif self.radioButton_27.isChecked():
            points4+=10
        elif self.radioButton_3.isChecked():
            points5+=10   
        elif self.radioButton_6.isChecked():
            points1+=10
        elif self.radioButton_5.isChecked():
            points2+=10
        elif self.radioButton_29.isChecked():
            points3+=10
        elif self.radioButton_30.isChecked():
            points4+=10
        elif self.radioButton_28.isChecked():
            points5+=10   


        elif self.radioButton_10.isChecked():
            points1+=10
        elif self.radioButton_7.isChecked():
            points2+=10
        elif self.radioButton_8.isChecked():
            points3+=10
        elif self.radioButton_9.isChecked():
            points4+=10
        elif self.radioButton_35.isChecked():
            points5+=10   



        elif self.radioButton_11.isChecked():
            points1+=10
        elif self.radioButton_12.isChecked():
            points2+=10
        elif self.radioButton_32.isChecked():
            points3+=10
        elif self.radioButton_13.isChecked():
            points4+=10
        elif self.radioButton_33.isChecked():
            points5+=10   

        elif self.radioButton_14.isChecked():
            points1+=10
        elif self.radioButton_15.isChecked():
            points2+=10
        elif self.radioButton_16.isChecked():
            points3+=10
        elif self.radioButton_31.isChecked():
            points4+=10
        elif self.radioButton_17.isChecked():
            points5+=10  

        elif self.radioButton_18.isChecked():
            points1+=10
        elif self.radioButton_19.isChecked():
            points2+=10
        elif self.radioButton_20.isChecked():
            points3+=10
        elif self.radioButton_21.isChecked():
            points4+=10
        elif self.radioButton_34.isChecked():
            points5+=10  
            
        self.label.hide()
        self.label_10.hide()
        self.label_11.hide()
        self.label_12.hide()
        self.label_13.hide()
        self.label_14.hide()
        self.label_2.hide()
        self.label_3.hide()
        self.label_4.hide()
        self.label_5.hide()
        self.label_6.hide()
        self.label_7.hide()
        self.label_8.hide()
        self.label_9.hide()
        self.label_16.hide()
        self.label_18.hide()
        self.label_19.hide()
        self.label_21.hide()
        self.radioButton.hide()
        self.radioButton_2.hide()
        self.radioButton_3.hide()
        self.radioButton_4.hide()
        self.radioButton_5.hide()
        self.radioButton_6.hide()
        self.radioButton_7.hide()
        self.radioButton_8.hide()
        self.radioButton_9.hide()
        self.radioButton_10.hide()
        self.radioButton_11.hide()
        self.radioButton_12.hide()
        self.radioButton_13.hide()
        self.radioButton_14.hide()
        self.radioButton_15.hide()
        self.radioButton_16.hide()
        self.radioButton_17.hide()
        self.radioButton_18.hide()
        self.radioButton_19.hide()
        self.radioButton_20.hide()
        self.radioButton_21.hide()
        self.radioButton_22.hide()
        self.radioButton_23.hide()
        self.radioButton_24.hide()
        self.radioButton_25.hide()
        self.radioButton_26.hide()
        self.radioButton_27.hide()
        self.radioButton_28.hide()
        self.radioButton_29.hide()
        self.radioButton_30.hide()
        self.radioButton_31.hide()
        self.radioButton_32.hide()
        self.radioButton_33.hide()
        self.radioButton_34.hide()
        self.radioButton_35.hide()
        self.pushButton.hide()
        self.label_11.show() 
        self.label_16.show()
    
        

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1224, 862)
        MainWindow.setStyleSheet("background-color:grey;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, -10, 291, 51))
        self.label.setStyleSheet("color:white;\n"
"font-family: \"Gill Sans Extrabold\", sans-serif;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 70, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(720, 70, 55, 16))
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 171, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_22 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_22.setObjectName("radioButton_22")
        self.verticalLayout.addWidget(self.radioButton_22)
        self.radioButton_23 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_23.setObjectName("radioButton_23")
        self.verticalLayout.addWidget(self.radioButton_23)
        self.radioButton_24 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_24.setObjectName("radioButton_24")
        self.verticalLayout.addWidget(self.radioButton_24)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(650, 100, 201, 130))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_25 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_25.setObjectName("radioButton_25")
        self.verticalLayout_2.addWidget(self.radioButton_25)
        self.radioButton_26 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_26.setObjectName("radioButton_26")
        self.verticalLayout_2.addWidget(self.radioButton_26)
        self.radioButton_27 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_27.setObjectName("radioButton_27")
        self.verticalLayout_2.addWidget(self.radioButton_27)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(900, 70, 131, 16))
        self.label_4.setObjectName("label_4")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(870, 100, 201, 138))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_3.addWidget(self.radioButton_6)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_28 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_28.setObjectName("radioButton_28")
        self.verticalLayout_3.addWidget(self.radioButton_28)
        self.radioButton_29 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_29.setObjectName("radioButton_29")
        self.verticalLayout_3.addWidget(self.radioButton_29)
        self.radioButton_30 = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.radioButton_30.setObjectName("radioButton_30")
        self.verticalLayout_3.addWidget(self.radioButton_30)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 360, 161, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(470, 70, 121, 16))
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(320, 390, 181, 141))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_4.addWidget(self.radioButton_10)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_4.addWidget(self.radioButton_8)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_4.addWidget(self.radioButton_7)
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_4.addWidget(self.radioButton_9)
        self.radioButton_35 = QtWidgets.QRadioButton(self.verticalLayoutWidget_4)
        self.radioButton_35.setObjectName("radioButton_35")
        self.verticalLayout_4.addWidget(self.radioButton_35)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(420, 100, 211, 131))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_5.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_5.addWidget(self.radioButton_12)
        self.radioButton_32 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_32.setObjectName("radioButton_32")
        self.verticalLayout_5.addWidget(self.radioButton_32)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_5.addWidget(self.radioButton_13)
        self.radioButton_33 = QtWidgets.QRadioButton(self.verticalLayoutWidget_5)
        self.radioButton_33.setObjectName("radioButton_33")
        self.verticalLayout_5.addWidget(self.radioButton_33)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 70, 81, 16))
        self.label_8.setStyleSheet("font-family: \"Gill Sans Extrabold\", sans-serif;")
        self.label_8.setObjectName("label_8")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(200, 100, 201, 131))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_6.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_6.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout_6.addWidget(self.radioButton_16)
        self.radioButton_31 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_31.setObjectName("radioButton_31")
        self.verticalLayout_6.addWidget(self.radioButton_31)
        self.radioButton_17 = QtWidgets.QRadioButton(self.verticalLayoutWidget_6)
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout_6.addWidget(self.radioButton_17)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 360, 181, 16))
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(590, 390, 171, 141))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.radioButton_18 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_18.setObjectName("radioButton_18")
        self.verticalLayout_7.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_19.setObjectName("radioButton_19")
        self.verticalLayout_7.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_20.setObjectName("radioButton_20")
        self.verticalLayout_7.addWidget(self.radioButton_20)
        self.radioButton_21 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_21.setObjectName("radioButton_21")
        self.verticalLayout_7.addWidget(self.radioButton_21)
        self.radioButton_34 = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        self.radioButton_34.setObjectName("radioButton_34")
        self.verticalLayout_7.addWidget(self.radioButton_34)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(260, 740, 631, 28))
        self.pushButton.setStyleSheet("  box-sizing: border-box;\n"
"  -webkit-appearance: none;\n"
"     -moz-appearance: none;\n"
"          appearance: none;\n"
"  background-color: transparent;\n"
"  border: 2px solid \"white\";\n"
"  border-radius: 0.6em;\n"
"  color: \"white\";\n"
"  cursor: pointer;\n"
"  display: -webkit-box;\n"
"  display: -webkit-flex;\n"
"  display: -ms-flexbox;\n"
"  display: flex;\n"
"  -webkit-align-self: center;\n"
"      -ms-flex-item-align: center;\n"
"          align-self: center;\n"
"  font-size: 1rem;\n"
"  font-weight: 400;\n"
"  line-height: 1;\n"
"  margin: 20px;\n"
"  padding: 1.2em 2.8em;\n"
"  text-decoration: none;\n"
"  text-align: center;\n"
"  text-transform: uppercase;\n"
"  font-family: \'Montserrat\', sans-serif;\n"
"  font-weight: 700;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(500, 700, 55, 16))
        self.label_18.setObjectName("label_18")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 820, 55, 16))
        self.label_5.setObjectName("label_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 810, 55, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 790, 301, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(280, -40, 671, 611))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("mai-littl-poniюозп.jpg"))
        self.label_12.setObjectName("label_12")
        self.label_12.hide()
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(280, 590, 661, 191))
        self.label_13.setObjectName("label_13")
        self.label_13.hide()
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(470, 30, 531, 541))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Без названия.jpg"))
        self.label_14.setObjectName("label_14")
        self.label_14.hide()
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(470, 160, 401, 281))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("asddsd.jpg"))
        self.label_16.setObjectName("label_16")
        self.label_16.hide()
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(440, 190, 431, 291))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("Без названия (2).jpg"))
        self.label_19.setObjectName("label_19")
        self.label_19.hide()
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(370, 160, 611, 351))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("grec-sk.jpg"))
        self.label_21.hide()
        self.label_21.setObjectName("label_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1224, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">тест какая ты дверь</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "дверь?"))
        self.label_3.setText(_translate("MainWindow", "зачем"))
        self.radioButton.setText(_translate("MainWindow", "дверь"))
        self.radioButton_2.setText(_translate("MainWindow", "орех"))
        self.radioButton_22.setText(_translate("MainWindow", "кпк"))
        self.radioButton_23.setText(_translate("MainWindow", "АТБ"))
        self.radioButton_24.setText(_translate("MainWindow", "автомат с конфетами"))
        self.radioButton_3.setText(_translate("MainWindow", "та хз"))
        self.radioButton_4.setText(_translate("MainWindow", "а зачем?"))
        self.radioButton_25.setText(_translate("MainWindow", "почему"))
        self.radioButton_26.setText(_translate("MainWindow", "по приказу двери"))
        self.radioButton_27.setText(_translate("MainWindow", "ради великого рода поней"))
        self.label_4.setText(_translate("MainWindow", "твое любимое аниме?"))
        self.radioButton_6.setText(_translate("MainWindow", "Дверь"))
        self.radioButton_5.setText(_translate("MainWindow", "ДжоДжо"))
        self.radioButton_28.setText(_translate("MainWindow", "блич"))
        self.radioButton_29.setText(_translate("MainWindow", "винкс"))
        self.radioButton_30.setText(_translate("MainWindow", "май литл пони"))
        self.label_6.setText(_translate("MainWindow", "ваше любимое животное"))
        self.label_7.setText(_translate("MainWindow", "когда вы родились"))
        self.radioButton_10.setText(_translate("MainWindow", "дверь"))
        self.radioButton_8.setText(_translate("MainWindow", "gtx 950"))
        self.radioButton_7.setText(_translate("MainWindow", "бутылка бомжоми"))
        self.radioButton_9.setText(_translate("MainWindow", "бомж"))
        self.radioButton_35.setText(_translate("MainWindow", "шрек"))
        self.radioButton_11.setText(_translate("MainWindow", "2008"))
        self.radioButton_12.setText(_translate("MainWindow", "ну дверь"))
        self.radioButton_32.setText(_translate("MainWindow", "до н.э"))
        self.radioButton_13.setText(_translate("MainWindow", "2010"))
        self.radioButton_33.setText(_translate("MainWindow", "другое"))
        self.label_8.setText(_translate("MainWindow", "кто ты по зз"))
        self.radioButton_14.setText(_translate("MainWindow", "дверь"))
        self.radioButton_15.setText(_translate("MainWindow", "лев, козерог дева"))
        self.radioButton_16.setText(_translate("MainWindow", "шрексукксуал"))
        self.radioButton_31.setText(_translate("MainWindow", "Аврора"))
        self.radioButton_17.setText(_translate("MainWindow", "другое"))
        self.label_9.setText(_translate("MainWindow", "кто вы по гендеру"))
        self.radioButton_18.setText(_translate("MainWindow", "дверь"))
        self.radioButton_19.setText(_translate("MainWindow", " Apache HTTP Server"))
        self.radioButton_20.setText(_translate("MainWindow", "натурал"))
        self.radioButton_21.setText(_translate("MainWindow", "гей"))
        self.radioButton_34.setText(_translate("MainWindow", "керамичиская плитка"))
        self.pushButton.setText(_translate("MainWindow", "узнать результат"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">Вы пони</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:6pt;\">сделано при поддержке американских спецслужб</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">Вы флатершай</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
